src/schema.js
Fixes the broken exports statement.
=> Fixes #1 Error when loading the graphiql window.

.gitignore, README.md, docker-compose.yml, package.json, src/schema.js
=> Add debugging support

repositories/QuestionnaireRepository.js, schema/types/Questionnaire.js, tests/fixtures/queries.gql
* also, remove ability to update surveyId through QuestionnaireRepository
=> expose surveyId on Questionnaire type

app.js, docker-compose.yml, package.json, yarn.lock
This is a new branch off the master with the changes made in the WIP-Apollo-Server branch due to the amount of changes in PR#5 making it too difficult to rebase against.
For reference old PR can be found [here](https://github.com/ONSdigital/eq-author-api/pull/7)
=> New branch for apollo migration

scripts/run_app.sh
This PR adds the migration command to the docker file inside the scripts/run_app.sh.
To test this stop and delete the docker image and run it again to run the migration and check to see if the tables are created inside postgres.
=> Added migrations to docker build

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Added github issue and pr templates
=> Issue and pr templates

repositories/PageRepository.js
Allows deletion of a `Page` without having to know `pageType` (e.g. so no need to call `deleteQuestionPage`)
test with accompanying PR in author
=> make deletePage work

.dockerignore, .travis.yml, Dockerfile, docker-compose.yml, docker-entrypoint.sh
Modified the travis build scripts to build and push the docker image to DockerHub. Also optimised the Dockerfile for standalone usage.
Check that the tag is created in DockHub for the PR `onsdigital/eq-author-api`
Test that the "Run using Docker" section of the README still works
=> Modify travis to push to DockerHub

db/Option.js, migrations/20170810155613_create_options_table.js, package.json, repositories/AnswerRepository.js, repositories/OptionRepository.js, repositories/index.js, schema/index.js, schema/resolvers.js, tests/schema/mutations/createAnswer.test.js, yarn.lock
This PR is currently WIP, but is intended to add the desired functionality to the real API in order to support Options.
Can create, update and remove Options correctly using the API.
=> Add options to the real API

Dockerfile, db/Option.js, docker-compose.yml, docker-entrypoint.sh, migrations/20170810155613_create_options_table.js, package.json, repositories/AnswerRepository.js, repositories/OptionRepository.js, repositories/index.js, schema/index.js, schema/resolvers.js, tests/schema/mutations/createAnswer.test.js, yarn.lock
This PR adds Options to the API and also introduces some changes to both the Docker configuration and package.json scripts so that DB migrations are performed automatically on `yarn start`.
This latter change was required in order for DB migrations to happen automatically as the application is deployed to CloudFoundry.
At the moment, DB migrations are done manually on CloudFoundry.
This PR has all of the same changes as #25 . It has been already been reviewed.
It can be merged as long as the build passes.
=> Add options to api

Dockerfile, migrations/20170908115223_remove_mandatory_from_question.js, package.json, repositories/QuestionPageRepository.js, tests/fixtures/data.json, tests/fixtures/queries.gql, tests/schema/mutations/createQuestionPage.test.js, tests/schema/mutations/updateQuestionPage.test.js, yarn.lock
[Trello card](https://trello.com/c/WzXFGP4i/110-remove-mandatory-field-from-questions-1)
- removes `mandatory` field from `Question`
- ensure tests pass
- test with author tool
=> Remove `mandatory` from Question

repositories/QuestionPageRepository.js, schema/resolvers.js
This PR removes some references to the `type` field that were missed in #31 .
All tests should pass.
The author app should no longer complain about `type`.
=> Remove some spurious references to type.

docker-compose.yml, package.json, schema/resolvers.js, yarn.lock
**DO NOT MERGE UNTIL SCHEMA MERGED**
Backwards-compatible changes to use `ID` type for entity id's, and input types for all mutations
run tests, examine changes, test against master of `eq-author` and [associated PR](https://github.com/ONSdigital/eq-author/pull/211) (to ensure it is compatible with both)
=> Improve graphql usage

migrations/20171023153048_add_date_range_answer_type.js
Created a migration to add `DateRange` to `Answer.type` enum
Review code, run migration, check that DateRange can be added to Answers table
=> add migration for daterange answer type

package.json, yarn.lock
Forgot to update schema in `package.json` as I had used `yarn link` locally.
Eyeball it
=> update to latest schema

migrations/20171211100317_add_created_by_to_questionnaires.js, package.json, repositories/QuestionnaireRepository.js, repositories/QuestionnaireRepository.test.js, schema/resolvers.js, tests/schema/mutations/createQuestionnaire.test.js, tests/schema/queries/questionnaire.test.js, yarn.lock
* Compliments changes in this PR: https://github.com/ONSdigital/eq-author-graphql-schema/pull/19
Tests pass, code looks good
=> 324 deeper auth integration

.eslintrc, README.md, config/knexfile.js, db/QuestionPage.js, docker-compose.yml, migrations/20180209121814_add_index_to_page_section_id.js, migrations/20180209121829_add_order_to_page_id.js, migrations/20180209165440_seed_page_order_column.js, package.json, repositories/PageRepository.js, repositories/PageRepository.test.js, repositories/QuestionPageRepository.js, repositories/QuestionnaireRepository.test.js, repositories/spacedOrderStrategy.js, schema/resolvers.js, scripts/test.sh, tests/schema/mutations/createQuestionPage.test.js, yarn.lock
Add functionality to allow pages to be reordered/moved/inserted at a specific position. 
Dependent on changes here: https://github.com/ONSdigital/eq-author-graphql-schema/pull/22
Run tests, check code is sensible
=> 378 reorder pages

README.md, config/settings.js, docker-compose.yml, repositories/PageRepository.test.js, repositories/spacedOrderStrategy.js, scripts/test.sh
Fixes the above bug.
I also noticed that some of the README was out of date (Debugging and Configuration sections), so I updated that too.
Tests pass, bug is observed to be fixed
=> Consistent move operations. fixes #53

app.js
=> Prevent logging requests to the /status route.

repositories/QuestionnaireRepository.js, repositories/QuestionnaireRepository.test.js
update to return questionnaires ordered by created date desc
n/a
=> sort questionnaires by date desc

repositories/PageRepository.js, repositories/PageRepository.test.js, repositories/strategies/spacedOrderStrategy.js, schema/resolvers.js
Adds ability to get `position` for a single page in isolation. Extract some common code for reuse.
Code looks good, tests pass
=> 343 move page tweaks

migrations/20180406083151_add_other_answer_id_to_options.js, package.json, repositories/OptionRepository.js, repositories/strategies/multipleChoiceOtherAnswerStrategy.js, schema/resolvers.js, schema/resolvers.test.js, tests/utils/graphql.js, yarn.lock
This PR is part of the change required in order implement the "add other option" feature.
This PR implements the necessary logic to resolve the "other" Option and BasicAnswer for a MultipleChoiceAnswer.
The strategy for creating the other Answer has also been updated so that the "other" Option is created and deleted along with the answer.
All tests and checks should pass. Code review required.
Once this PR is merged, there will be changes required in Author and Publisher.
=> Implement API changes in order to support add "other" option and text field answer.

repositories/PageRepository.test.js, repositories/QuestionnaireRepository.test.js, utils/mapFields.js, utils/mapFields.test.js
Describe what you have changed and why, link to other PRs or Issues as appropriate.
Describe the steps required to test the changes (include screenshots if appropriate).
=> handle non-existent other answer correctly

docker-compose.yml, package.json, repositories/RoutingRepository.js, repositories/strategies/routingStrategy.js, schema/resolvers.js, schema/resolvers.test.js, tests/utils/graphql.js, yarn.lock
What is the context of this PR?
This PR has been raised in order to revert some the changes made to routing and return it to being able to select multiple options per condition.
How to review
Tests pass, changes make sense.
=> Reverted api to allowing multiple options per condition

migrations/20180621140416_add_properties_to_answers.js, migrations/20180622154505_migrate_mandatory_field_data_to_properties.js, migrations/20180622160307_remove_mandatory_from_answers.js, migrations/20180706134843_add_decimals_data_to_properties.js, package.json, repositories/AnswerRepository.js, repositories/strategies/multipleChoiceOtherAnswerStrategy.js, schema/resolvers.js, schema/resolvers.test.js, tests/fixtures/data.json, tests/fixtures/queries.gql, tests/schema/mutations/createAnswer.test.js, tests/schema/mutations/updateAnswer.test.js, tests/utils/graphql.js, yarn.lock
This is part of a wider piece of work to introduce answer properties to help the quality of the respondent's input.  
Prior to this work, the concept of answer properties was limited to capturing whether or not an answer is 'mandatory'.  This concept has been refactored to support multiple properties and this PR specifically introduces 'decimal' properties.
[Trello Ticket](https://trello.com/c/f978JRq6/402-properties-decimals-1) 
This PR works in conjunction with the following PR's:
Web App - https://github.com/ONSdigital/eq-author/pull/376
Schema - ONSdigital/eq-author-graphql-schema#46
- Run Tests
=> Add properties to answers

repositories/strategies/multipleChoiceOtherAnswerStrategy.js, schema/resolvers.js, utils/defaultAnswerProperties.js
Other answer was defaulting to required: true when it was created, this caused issues in runner as it doesn't support this implementation. This Pr exports the function that defines the default properties to a util function so all defaults can come from the same place. 
Tests pass and the required field on other answers should correctly default to false.
=> Made 'other' answer default to required = false

migrations/20180720085104_add_view_for_composite_answers.js, package.json, repositories/AnswerRepository.js, repositories/OptionRepository.js, repositories/PageRepository.js, repositories/PageRepository.test.js, repositories/QuestionPageRepository.js, repositories/QuestionnaireRepository.js, repositories/QuestionnaireRepository.test.js, repositories/RoutingRepository.js, repositories/SectionRepository.js, repositories/strategies/multipleChoiceOtherAnswerStrategy.js, schema/resolvers.js, schema/resolvers.test.js, tests/schema/queries/answer.test.js, tests/schema/queries/answers.test.js, tests/schema/queries/option.test.js, tests/schema/queries/page.test.js, tests/schema/queries/questionPage.test.js, tests/schema/queries/questionnaire.test.js, tests/schema/queries/section.test.js, tests/utils/graphql.js, tests/utils/mockRepository.js, utils/childAnswerParser.js, yarn.lock
This PR works to split up a Date range answer into a composite answer type allowing the rest of the application to treat it as two separate answers.
Tests pass and the new Composite type works.
=> Implementing Date Range composite methods.

db/Validation.js, docker-compose.yml, migrations/20180730084336_add_tables_for_validations.js, package.json, repositories/AnswerRepository.js, repositories/OptionRepository.js, repositories/ValidationRepository.js, repositories/index.js, repositories/strategies/validationStrategy.js, schema/resolvers.js, schema/resolvers.test.js, schema/resolversTests/validation.test.js, tests/schema/mutations/createAnswer.test.js, tests/utils/graphql.js, tests/utils/mockRepository.js, utils/defaultAnswerValidations.js, yarn.lock
This PR implements the changes required in order to mutate and retrieve data regarding minimum and maximum value mutations. It includes new resolvers, new strategies and methods in the repositories and finally also includes db mutations required to add the minValue and maxValue data to our db schema.  
Tests all pass, and using the graphiql interface all minValue and maxValue data should be retrievable.
=> Validation min and max value API changes

migrations/20180823133327_add_mutually_exclusive_option_bool.js, package.json, repositories/OptionRepository.js, schema/resolvers.js, schema/resolvers.test.js, tests/schema/queries/answer.test.js, tests/utils/graphql.js, yarn.lock
This Pr adds the required resolvers, methods, migrations and tests to ensure that mutually exclusive answers can be created in the database. 
Tests pass and are conclusive, exclusive answers can be created on the back end.
https://github.com/ONSdigital/eq-author-graphql-schema/pull/56
=> Mutually exclusive answer options

schema/resolvers.js, schema/resolvers.test.js, tests/schema/queries/metadata.test.js
Fixes reference to a historic foreign key in the database
- Run Tests
=> Fix reference to historic foreign key in database

repositories/MetadataRepository.js, repositories/MetadataRepository.test.js, utils/defaultMetadata.js
Adds default values when updating Metadata
- Run tests
- Ensure default values are populate as expected
=> Add default metadata

migrations/20180919111921_adding_date_validations_to_existing_answers.js, schema/resolversTests/validation.test.js, utils/defaultAnswerValidations.js
Adds new migration to fix the database not being correctly initialised with new date validations. Also changes the default latest date validation config to bring it into line with designs.
Tests pass, migration runs correctly and all existing date answers gain earliest and latest validations.
=> Fix data migration for date validation

package.json, yarn.lock
Upgrade to Husky 1.0.1
Run tests make sure they pass
=> Upgrade to Husky 1.0.1

.eslintrc, package.json, yarn.lock
- Upgrades to latest [eslint](https://www.npmjs.com/package/eslint) and  [eslint-config-eq-author](https://www.npmjs.com/package/eslint-config-eq-author)
- Ensure tests pass
- Ensure [new linting rules](https://github.com/ONSdigital/eslint-config-eq-author/pull/7) work as expected
=> Upgrade eslint and eslint config

repositories/PageRepository.test.js, repositories/SectionRepository.js, repositories/SectionRepository.test.js, repositories/strategies/duplicateStrategy.js, repositories/strategies/duplicateStrategy.test.js, schema/resolvers.js, schema/resolversTests/duplication.test.js
Duplicating sections
1. Pull this and the UI change https://github.com/ONSdigital/eq-author/pull/454
1. Ensure you can duplicate a section with questions, answers and validations.
=> 647 - Duplicating sections

repositories/strategies/duplicateStrategy.js, repositories/strategies/duplicateStrategy.test.js
Duplicate metadata in a questionnaire
1. Checkout author branch `551-duplicate-questionnaire`
1. Create a questionnaire with metadata
1. Duplicate a questionnaire
1. Ensure that the metadata is duplicated
=> 678 - Duplicate questionnaire metadata

migrations/20181004135102_add_custom_values_to_routing_condition_values.js, package.json, repositories/RoutingRepository.js, repositories/strategies/routingStrategy.js, schema/resolvers.js, schema/resolvers.test.js, tests/utils/graphql.js, utils/migrateEnumChecks.js, yarn.lock
Api backend changes to implement routing based on a number.
Tests pass and the new functionality works.
=> 656 api changes for routing based on number

repositories/RoutingRepository.js, repositories/strategies/routingStrategy.js, schema/resolvers.test.js
After linking the api into the front end changes a couple of small issues came to light, this PR resolves those issues and adds a test case to stop it from happening in future.
Tests pass and code changes look good.
=> Fixed the bugs discovered after testing the front-end with the api

constants/validation-entity-types.js, migrations/20181004142958_add_entity_type_to_validation_answer_rules.js, migrations/20181024112053_update_validation_entity_type_enums.js, migrations/20181024112700_add_metadata_id_to_validation_answer_rules.js, package.json, repositories/ValidationRepository.js, schema/resolvers.js, schema/resolversTests/validation.test.js, tests/schema/mutations/createMetadata.test.js, tests/utils/graphql.js, yarn.lock
- Adds validation against metadata for earliest and latest date 
- Run tests
```
#Earliest date
mutation updateValidationRule($input: UpdateValidationRuleInput!) {
updateValidationRule(input: $input) {
...EarliestDateValidationRule
__typename
}
}
fragment EarliestDateValidationRule on EarliestDateValidationRule {
id
enabled
entityType
customDate: custom
offset {
value
unit
__typename
}
relativePosition
previousAnswer {
id
displayName
__typename
}
metadata {
id
displayName
__typename
}
__typename
}
{
"input":{
"id":"3",
"earliestDateInput":{
"offset":{
"value":10,
"unit":"Days"
},
"relativePosition":"Before",
"entityType":"PreviousAnswer",
"custom":null,
"previousAnswer": null,
"metadata": "1"
}
}
}
``` …
=> 694 validation metadata earliest latest date

constants/validation-entity-types.js, migrations/20181031140447_added_now_to_validation_enum.js, package.json, repositories/strategies/validationStrategy.js, schema/resolversTests/validation.test.js, utils/defaultAnswerValidations.js, yarn.lock
This PR adds a migration to allow us to validate based on the current date and also adds the methods required to do this.
Changes make sense and tests pass.
=> Implemented ablity to validate latest on Now

README.md, app.js, middleware/import.js, repositories/strategies/duplicateStrategy.test.js, tests/utils/buildTestQuestionnaire.js
This adds the ability to import questionnaires from other environments to dev. It isn't quick and takes about 5 seconds to import UKIS into my dev env.
1.  Run the following query against an environment to get the data for a questionnaire.
```graphql
fragment answerFragment on Answer {
id
type
label
description
guidance
properties
qCode
...on BasicAnswer{
validation{
...on NumberValidation{
minValue{
id
inclusive
enabled
custom
}
maxValue{
id
inclusive
enabled
custom
entityType
previousAnswer {
id
}
}
}
...on DateValidation{
earliestDate{
id
enabled
custom
offset {
value
unit
}
relativePosition
}
latestDate{
id
enabled
custom
offset {
value
unit
}
relativePosition
}
}
}
}
...on CompositeAnswer{
childAnswers{
id
label
}
}
}
fragment optionFragment on Option {
id
label
description
value …
```
=> Experimental - Import questionnaire

package.json, repositories/SectionRepository.test.js, repositories/strategies/duplicateStrategy/piping.js, repositories/strategies/duplicateStrategy/piping.test.js, schema/resolvers.js, schema/resolvers.test.js, tests/schema/mutations/updateSection.test.js, tests/utils/graphql.js, yarn.lock
Couple issues in the api meant that the section introduction resolvers weren't working correctly. This PR address those issues.
New tests pass and e2e implementation passes.
=> Section Introduction

tests/fixtures/queries.gql, tests/schema/mutations/createSection.test.js, tests/schema/mutations/updateAnswer.test.js, tests/schema/mutations/updateSection.test.js, tests/schema/queries/section.test.js, tests/utils/buildTestQuestionnaire.js, tests/utils/graphql.js
Removal of deprecated fields for Graphql v14 upgrade
Make sure tests pass
=> Removal of deprecated fields
