package.json, src/server.js, src/settings.js
CloudFoundry builds and runs the app, but it does not keep the dev dependencies around, so the package.json was updated so that dependencies are under the main runtime dependencies.
Also CloudFoundry needed the engines property as a hint to select the correct version of nodejs_buildpack.
=> Make changes to package.json for CloudFoundry.

repositories/QuestionnaireRepository.js, schema/mutations/updateQuestionnaire.js
This PR fixes #11 by re-introducing the `surveyId` argument in the UpdateQuestionnaire mutation.
There was a previous constraint on the API which prevented a survey Id from being updated.
This change removes that restriction.
Run the mutation queries via the GraphiQL interfaces (using Docker).
Observe that the Update Questionnaire mutation allows surveyId to be passed in.
Observe that the survey Id is updated when mutation is executed.
=> Fixes #11 Allow survey Id to be updated.

Dockerfile
One of the issues highlighted by codacy automated code review tool was the use of `apt-get upgrade` in the Dockerfile.
I had a look through the [Docker documentation for apt-get](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#apt-get) and it seems they advise against performing an upgrade.
Also, a `apt-get update` is only useful if we plan on installing custom packages to the Docker image.
Since we're not doing that at the moment, we can remove this. This should significantly speed up the process of building our Docker images.
`docker-compose build` should still work and able to run the API using Docker using `docker-compose up` as previous.
=> Remove apt-get upgrade from Dockerfile.

schema/resolvers.js, schema/typeDefinitions.js
* adds `groups` back for backwards compatibility
* uses `@deprecated` directive to notify clients of deprecation (e.g. graphiql shows it is deprecated, and gives reason for deprecation)
=> make backwards compatible

schema/resolvers.js, schema/typeDefinitions.js, tests/schema/mutations/createAnswer.test.js, tests/schema/mutations/createQuestionnaire.test.js, tests/utils/mockRepository.js
Creates a new section and page when a questionnaire is created. 
We realised while building the eq-author front-end that this is an implicit requirement when creating a questionnaire, and so the API should assume the responsibility rather than have the front-end make multiple sequential requests.
=> Create initial section & page

package.json, schema/resolvers.js, tests/schema/mutations/createAnswer.test.js, tests/schema/mutations/createPage.test.js, tests/schema/mutations/createQuestionPage.test.js, tests/schema/mutations/updateAnswer.test.js, tests/schema/mutations/updatePage.test.js, tests/schema/mutations/updateQuestionPage.test.js, tests/schema/queries/answer.test.js, tests/schema/queries/option.test.js, tests/schema/queries/page.test.js, tests/schema/queries/questionPage.test.js, tests/schema/queries/questionnaire.test.js, tests/schema/queries/section.test.js, yarn.lock
This PR removes foreign key details from leaking into the GraphQL API, by updating the resolvers to return references to the actual entities.
In practice what this allows you to do is browse the API as a graph of objects, so you can go in both directions, up and down the tree.
So for example, you can now do things like:
```
{
questionnaire(id: 1) {
title
sections {
id
questionnaire {
title
}
}
}
}
```
in the above example, both `title` attributes should be equal.
This PR is not ready for merge until the schema and the front-end changes have been completed.
They will be worked on in separate PRs.
=> Change api to return objects

migrations/20170911160138_remove_type_from_questionpage.js, package.json, tests/schema/mutations/createQuestionPage.test.js, tests/schema/mutations/updateQuestionPage.test.js, yarn.lock
This PR has all of the API changes necessary to remove the type field from the QuestionPage GraphQL Schema type.
This change removes all references to `type` from queries and resolvers present in the Author API.
It also introduces a database migration script that can be used to drop the appropriate column on the Pages table.
All tests should pass.
There should be no references to `type` on the QuestionPage related objects.
The database migration script should behave as expected.
=> Remove type from question

package.json
When CF launches the application it runs the default start script.
We need to ensure that the `yarn upgrade eq-author-graphql-schema` command is run before starting.
Should not affect application behaviour.
=> Ensure eq-survey-graphql-schema is upgraded before application starts.

migrations/20170925095226_change_integer_types_to_number.js, package.json, yarn.lock
Update the API to use the latest GraphQL schema.
Add migration which alters the constraint check on the `type` field of the `Answers` table.
Allowable values after migration have been changed from `Integer` and `PositiveInteger` to `Number`.
All tests should pass.
=> Add edit number answer

package.json, schema/resolvers.js, tests/schema/mutations/createAnswer.test.js, tests/schema/mutations/createPage.test.js, tests/schema/mutations/createQuestionPage.test.js, tests/schema/mutations/createQuestionnaire.test.js, tests/schema/mutations/createSection.test.js, tests/schema/mutations/deleteAnswer.test.js, tests/schema/mutations/deletePage.test.js, tests/schema/mutations/deleteQuestionPage.test.js, tests/schema/mutations/deleteQuestionnaire.test.js, tests/schema/mutations/deleteSection.test.js, tests/schema/mutations/updateAnswer.test.js, tests/schema/mutations/updatePage.test.js, tests/schema/mutations/updateQuestionPage.test.js, tests/schema/mutations/updateQuestionnaire.test.js, tests/schema/mutations/updateSection.test.js, tests/schema/queries/answer.test.js, tests/schema/queries/option.test.js, tests/schema/queries/page.test.js, tests/schema/queries/questionPage.test.js, tests/schema/queries/questionnaire.test.js, tests/schema/queries/section.test.js, yarn.lock
Cleans up some changes from previous PR, which were to ensure backwards compatibility
* now exclusively uses input types for mutations
* updates test to reflect `id` fields are now type `ID`
Run tests, sanity-check code
=> accept input types only for mutations, fix tests

app.js, config/settings.js, package.json, yarn.lock
This PR adds some HTTP logging to the Author API using the `morgan` package. This is the same HTTP logging package used in Publisher.
This PR also does some tidying up refactoring of the API by removing some unnecessary environment variables.
HTTP logs should be displayed when making requests to the API.
=> Add basic HTTP logging to the API and a bit of refactoring.

config/knexfile.js, db/Answer.js, db/Option.js, db/Page.js, db/QuestionPage.js, db/Questionnaire.js, db/Section.js, migrations/20171024153850_add_soft_delete.js, package.json, repositories/AnswerRepository.js, repositories/OptionRepository.js, repositories/PageRepository.js, repositories/QuestionPageRepository.js, repositories/QuestionnaireRepository.js, repositories/QuestionnaireRepository.test.js, repositories/SectionRepository.js, schema/resolvers.js, yarn.lock
This PR makes changes to the API, namely in the repositories and DB access layer to support soft deleting of Questionnaires, Sections, Pages, Answers and Options.
A new DB migration script has been included which adds a new column `state`. For now possible values for `state` are `Active` (the default value), and `Deleted`.
In future, there may be additional states such as 'Archived' or 'Locked' but that is not in scope for now.
A new integration test has been introduced to test soft deletion at the Questionnaire level.
When running the author against this branch, deleting a Questionnaire, Section, Question, Answer or Option should mark the correct record as being "Deleted".
The deleted element should no longer appear when using the application. The deleted element can be restored by …
=> 205 undo deletes

schema/resolvers.js, tests/schema/queries/answers.test.js
* Switch to using [npm published schema](https://www.npmjs.com/package/eq-author-graphql-schema)
* To support piping, implements `answers` query defined in schema.
* Add tests
Review code, run tests, test new query in graphiql
=> Add answers query to support piping feature.

README.md, migrations/20171116131851_add_summary_column.js, package.json, repositories/QuestionnaireRepository.js, repositories/QuestionnaireRepository.test.js, yarn.lock
This PR makes changes to the API in order to support the new `summary` property on Questionnaires.
All tests and checks should pass.
It should be possible to persist and retrieve the `summary` property for a Questionnaire after applying this PR.
=> Add summary property to Questionnaire in the API.

.travis.yml, Dockerfile
This PR updates the travis configuration so that API builds and tests run in a Node 8 (LTS) environment.
The docker configuration has also been updated so that the API runs using Node 8
All tests and checks should pass.
Visual inspection of travis build log to ensure Node 8 is being used.
Pull down docker image for this branch and inspect it to make sure it is using Node 8 and that it runs as expected.
=> Upgrade API to run using Node 8.

.travis.yml, package.json, yarn.lock
Travis seems to generate its own lockfile instead of using the one in the github repo. Which means tests can pass on travis but not be up to date when run locally.
Travis should fail if the lock-file is out of date with the package.json file and should pass if the inverse is true.
=> Forced yarn install step to use frozen lockfile on travis

repositories/strategies/multipleChoiceOtherAnswerStrategy.js, schema/resolvers.test.js, tests/utils/graphql.js
There is an issue where null values are being returned for other answer description.
This change to the API should ensure that other answers have an empty string
description by default.
This is only an issue because the other answer is a hidden field. So users cannot
provide a value.
- Code changes look good.
- All tests pass.
=> Fixes null description passed through for `other` answer.

db/Page.js, migrations/20180501142343_add_view_table_for_pages.js, repositories/PageRepository.js, repositories/PageRepository.test.js, repositories/strategies/spacedOrderStrategy.js
* Simplifies some awkward logic around computing the `position` value for pages. Possibly needs some indexes or something added. Need to investigate further. But for now the code works
* Simplifies logic around calculating `order` values when moving pages
* Reduces number of round trips to DB, at cost of bigger payload from DB
* Improves performance of inserts - previously would insert at end of list, _then_ perform a move operation to place at correct position. Now inserts directly at correct position
Run tests. Run e2e tests. Check code is sensible
=> Improvements to move page feature

Dockerfile, db/Routing.js, docker-compose.yml, migrations/20180430155015_creating_routing_databases.js, package.json, repositories/AnswerRepository.js, repositories/OptionRepository.js, repositories/PageRepository.js, repositories/RoutingRepository.js, repositories/index.js, repositories/strategies/routingStrategy.js, repositories/strategies/routingStrategy.test.js, schema/resolvers.js, schema/resolvers.test.js, tests/utils/graphql.js, utils/formatRichText.js, utils/formatRichText.test.js, yarn.lock
This PR adds necessary resolvers for the newly introduced GraphQL schema types in order to support basic routing functionality within Author.
Changes include:
- New migration scripts to create the new database tables.
- Resolver functions for each of the new GraphQL types for basic routing.
- Database and transaction logic (Repository, queries etc.)
- New integration and unit tests covering the core routing logic.
- New field arguments to support bringing back section and page titles as plaintext.
All checks and tests should pass.
Code review required.
- https://github.com/ONSdigital/eq-author-graphql-schema/pull/37
=> Implement routing on api

package.json, yarn.lock
Author API is failing to deploy in both staging and pre-production environments due to a mismatch in the semantic versions of the graphql schema.
This PR pins the API to a version of the schema known to be working.
API should be pinned to version 0.15.0
All tests and checks should pass.
=> Pin author api to working version of the schema.

repositories/strategies/routingStrategy.js
Noticed that occasionally the `Section`s were coming back from `availableRoutingDestinations` in the wrong order. This PR adds an `ORDER BY created_at ASC` clause to the query (since sections have no user-defined order yet).
I had a problem recreating the issue locally. It seems to happen inconsistently on pre-prod, and i'm not sure what circumstances cause it...
This questionnaire _has_ the issue: https://deploy-preview-364--author.netlify.com/#/eq-author/questionnaire/150/424/1578/routing
This questionnaire _does not_ have the issue: https://deploy-preview-364--author.netlify.com/#/eq-author/questionnaire/149/418/1567/routing
However, I think this is the right change and is safe to make regardless (this is how things are ordered in `SectionRepository`)
=> ensure sections are ordered in availableRoutingDestinations

migrations/20180629130216_add_order_to_sections.js, migrations/20180629130217_seed_section_order_column.js, migrations/20180711133028_add_view_table_for_sections.js, repositories/PageRepository.js, repositories/PageRepository.test.js, repositories/SectionRepository.js, repositories/SectionRepository.test.js, repositories/strategies/spacedOrderStrategy.js, schema/resolvers.js, schema/resolvers.test.js, tests/utils/graphql.js
- Implements functionality required to re-order and move sections within a questionnaire
- Run Tests
```
mutation MoveSection($input: MoveSectionInput!) {
moveSection(input: $input) {
id
position
__typename
}
}
{
"input": {
"id": "1",
"questionnaireId": "1",
"position": 2
}
}
```
=> Add move section mutation

package.json, repositories/SectionRepository.js, repositories/SectionRepository.test.js, schema/resolvers.js, schema/resolvers.test.js, yarn.lock
- Resolves new type `QuestionnaireInfo` which returns total number of sections in a questionnaire
- This is needed to be able to disable/enable the 'Move Section' button on the UI to based on the number of sections in a questionnaire.
- https://trello.com/c/18p5lgJP/533-disable-move-section-button-if-there-is-only-one-section
- Run Tests
- Use eQ Author GraphQL API explorer to query QuestionnaireInfo eg.
```
query GetTotalSectionCount($id: ID!) {
questionnaire(id: $id) {
questionnaireInfo {
totalSectionCount
}
}
}
{
"id": 1
}
```
=> Add query resolver to get total number of sections in a questionnaire

package.json, repositories/SectionRepository.js, repositories/SectionRepository.test.js, schema/resolvers.js, yarn.lock
- Upgrades graphql schema which deprecates section description field as it is redundant and never used by eq-runner
- Stops adding section description content when creating a questionnaire
- Section description will remain in the DB schema and repository methods whilst the field is still supported
- Run tests
- Ensure sections can still be queried and mutated with / without section descriptions
GraphQL Schema - https://github.com/ONSdigital/eq-author-graphql-schema/pull/51
=> Upgrade schema and stop adding section description content

migrations/20180809154832_add_date_format_data_to_properties.js, schema/resolversTests/properties.test.js, utils/defaultAnswerProperties.js
Introduces `Date Format` property for answer type `Date`.
- Run Tests
- Use eQ Author GraphQL API explorer to test mutations and queries to ensure `format` property is udpated eg.
```
mutation UpdateAnswer($input: UpdateAnswerInput!) {
updateAnswer(input: $input) {
...Answer
__typename
}
}
fragment Answer on Answer {
id
description
guidance
label
type
properties
__typename
}
{ 
"input": {
"id": "1", 
"properties": {
"format": "mm/yyyy", 
"required": true
}
}
}
```
=> 554 Date Format Picker

schema/resolvers.js
Returns null from the validation node in basic answers for all non-number answer types.
Run tests
=> Allow non-number answers to return null from validation resolver.

migrations/20180822122408_add_min_max_validation_to_existing_number_currency_answers.js
The changes made to the api during the addition of min value validation were not backwards compatible as no data was being created for the existing answers.
This PR aims to add a mutation which can add empty data to all existing answers that now need those validation rows.  
Test on database, add number answer, delete the validations, then run this migration.
Test using a large amount of data, quickest way I found to create the data was to use this mutation on the graphql client.
mutation{
createAnswer(input: {
type: Currency
questionPageId: 1
}){
id 
}
}
Then execute the following code in the browser:
` var b = document.querySelector("[class='execute-button']")`
`for (var i =0 ; i<2000; i++){
b.click()
}`
Finally delete everything in the validations database and run the mutation.
=> Added new migration

migrations/20180824093112_add_min_max_validation_to_existing_answers_v2.js
This previous PR attempt to add min and max validations to existing answers did not work as expected. For some reason the data was never updated in the database. This may have been because of promises not resolving correctly and so this PR adds a new migration that should ensure that all promises are resolved before the migration ends. It will also wipe all data in the validations table so that a fresh state can be ensured preventing any entries from becoming invalid.
Same as https://github.com/ONSdigital/eq-author-api/pull/107
=> Migration to add validations to existing answers.

db/Metadata.js, migrations/20180828155216_create_questionnaire_metadata_table.js, package.json, repositories/MetadataRepository.js, repositories/MetadataRepository.test.js, repositories/index.js, schema/resolvers.js, tests/schema/mutations/createMetadata.test.js, tests/schema/mutations/deleteMetadata.test.js, tests/schema/mutations/updateMetadata.test.js, tests/schema/queries/metadata.test.js, yarn.lock
Introduces `Metadata` to `Questionnaire`
- Run Tests
```
mutation CreateMetadata($input: CreateMetadataInput!) {
createMetadata(input: $input) {
id
}
}
{
"input": {
"questionnaireId": "1"
}
}
--
mutation UpdateMetadata($input: UpdateMetadataInput!) {
updateMetadata(input: $input) {
id
}
}
{
"input": {
"id": "1",
"key": "ru_ref",
"alias": "Reporting Unit Reference",
"type": "Text",
"textValue": "test"
}
}
--
query GetQuestionnaireWithMetadata($questionnaireId: ID!) {
questionnaire(id: $questionnaireId) {
id
metadata {
id
type
textValue
languageValue
regionValue
dateValue
}
}
}
{
"questionnaireId": 1
}
--
mutation DeleteMetadata($input: DeleteMetadataInput!) { …
```
=> 548 metadata

repositories/OptionRepository.js, repositories/PageRepository.js, repositories/PageRepository.test.js, repositories/QuestionnaireRepository.test.js, repositories/SectionRepository.test.js, repositories/strategies/duplicateStrategy.js, repositories/strategies/duplicateStrategy.test.js, schema/resolvers.js, schema/resolvers.test.js, schema/resolversTests/properties.test.js, schema/resolversTests/validation.test.js, scripts/test.sh, utils/updateTitle.js, utils/updateTitle.test.js
This PR adds the functionality in order to duplicate a page. 
>It also includes code for duplicating a section and questionnaire; these functions will not work just yet because some implementation for duplicating a page breaks these. This should be fixed in separate PRs because the additional functionality is not in scope for this ticket.
All tests should pass, and the code should work when calling the mutations included in [this schema PR](https://github.com/ONSdigital/eq-author-graphql-schema/pull/57)
=> 561 create mutation for duplicating a page

repositories/PageRepository.test.js, repositories/SectionRepository.test.js, repositories/strategies/spacedOrderStrategy.js
There is currently a bug on the move page api where trying to move a page forward creates unpredictable results this PR aims to bring the move page feature back into a working state.
New test passes and the move page feature works.
=> Fixed bug preventing move pages/sections from working

migrations/20180907155542_add_earliest_date_validation.js, migrations/20180910103658_convert_validation_custom_type.js, package.json, repositories/ValidationRepository.js, schema/resolvers.js, schema/resolversTests/validation.test.js, tests/utils/graphql.js, utils/defaultAnswerValidations.js, yarn.lock
1. Add earliest date validation to all date answers and new date answers
2. Allow for reading of the earliest date validation
3. Allow for updating of the config of an earliest date validation
Given you have a date answer with an ID of 19
```graphql
query QuestionPage($id: ID!) {
answer(id: $id) {
id
... on BasicAnswer {
validation {
... on DateValidation {
earliestDate {
id
enabled
custom
offset {
value
unit
}
relativePostion
}
}
}
}
}
}
```
Input:
```
{ "id": 19 }
```
Given you have an earliest date validation with ID 35
```graphql
mutation updateValidation($input: UpdateValidationRuleInput!) {
updateValidationRule(input: $input) {
id
enabled
... on EarliestDateValidationRule {
custom
offset {
value
unit
}
relativePostion
}
}
}
```
Input:
```json
{
"input":{
"id": 35, …
```
=> 449 - Earliest date validation

package.json, schema/resolvers.js, schema/resolvers.test.js, utils/getName.js, utils/getName.test.js, utils/html.js, utils/html.test.js, yarn.lock
We have inconsistent display values scattered through the author application. In some places, we display titles, in other places we display labels and in other places we have inconsistent unnamed or untitled placeholders.
This technical improvement makes it the responsibility of the API to provide the most relevant displayable value.
More info can be found here: https://github.com/ONSdigital/eq-author/wiki/Display-names
- Run tests
=> Implement displayTitle resolvers

migrations/20180918144616_add_alias_to_sections.js, package.json, repositories/SectionRepository.js, repositories/SectionRepository.test.js, tests/schema/mutations/createSection.test.js, tests/schema/mutations/updateSection.test.js, yarn.lock
- Adds `alias` field to `Sections`
- https://trello.com/c/fvYKd06w/571-aliases-for-sections-9
- Run tests
```
mutation CreateSection($input: CreateSectionInput!) {
createSection(input: $input) {
alias
}
}
{
"input": {
"title": "fooBarTitle",
"alias": "fooBarAlias",
"questionnaireId": "1"
}
}
```
```
mutation UpdateSection($input: UpdateSectionInput!) {
updateSection(input: $input) {
alias
}
}
{
"input": {
"id": "1",
"alias": "fooBarAlias"
}
}
```
```
query GetSection($id: ID!) {
section(id: $id) {
title
displayName
alias
}
}
{
"id": "1",
"alias": "fooBarAlias"
}
```
=> Add alias to Sections

package.json
A previous commit introduced a new dependency. This was not included in the package.json and caused a runtime error when trying to deploy to staging environment.
This PR adds the dependency to the package.json and therefore should install the dependency when building the container.
=> Fix missing js-yaml dependency.

package.json, schema/resolvers.js, tests/schema/queries/metadata.test.js, utils/getName.js, utils/getName.test.js, yarn.lock
Adds a displayName for metadata so we don't have to do this in the UI.
1. Ensure tests pass.
2. Ensure that metadata can be retrieved with a displayName
=> Add displayName for metadata

.dockerignore, Dockerfile, README.md, docker-entrypoint.sh, package.json
A change is required to the author API so that it is possible to read in secrets from an S3 bucket at runtime.
This is required because the signing and encryption keys used to create the JWT payload differ between dev, preprod and prod. The new launch mechanism works in staging at the moment due to the use of development keys, but will not currently work in pre-prod because the keys are not the same.
This change allows for overriding of the default behaviour with a new environment variable. This allows secrets to be read in from S3 at runtime.
I've also made a few optimisations to how we build the image to speed things up (e.g. no longer copying the contents of node_modules into the container) and updated the README with a few missing environment variable details.
- Build the docker image …
=> Modify docker config to read secrets from S3 bucket

package.json, yarn.lock
Upgrades `eslint-config-eq-author` which reduces severity level of `no-unused-vars` to warn
- Run tests
=> Upgrade eslint-config-eq-author

migrations/20181004142958_add_entity_type_to_validation_answer_rules.js, migrations/20181004143754_add_previous_answer_id_to_validation_answer_rules.js, package.json, repositories/ValidationRepository.js, schema/resolvers.js, schema/resolversTests/validation.test.js, tests/utils/graphql.js, yarn.lock
- Adds validation against a previous answer for max value 
- Run tests
```
mutation updateValidationRule($input: UpdateValidationRuleInput!) {
updateValidationRule(input: $input) {
...MaxValueValidationRule
__typename
}
}
fragment MaxValueValidationRule on MaxValueValidationRule {
id
enabled
custom
inclusive
entityType
previousAnswer {
id
displayName
__typename
}
__typename
}
{
"input": {
"id": "2", 
"maxValueInput": {
"inclusive": false, 
"previousAnswer": "1"
}
}
}
```
```
query answerWithValidation($id: ID!) {
answer(id: $id) {
... on BasicAnswer {
validation {
... on NumberValidation {
maxValue {
id
previousAnswer {
id
displayName
}
} 
}
}
}
}
}
{
"id": "2"
}
```
=> Add previous answer to max value

package.json, yarn.lock
Have run `yarn upgrade` this fixes:
1. Build errors on mac with `10.12.0` related to `fsevents`
1. Inability to run test watch with `10.12.0` on mac.
1. `docker-compose` `nodemon` file watching does not work.
Also have added new `nodemon` flag `-L` to get it to pick up file changes.
1. Ensure local node version is `10.12.0`
1. Prove on your local that file watching (with `yarn test --watch` and `docker-compose`) don't work on `master` after nuking `node_modules` and running `yarn`.
1. Switch to this branch - run `yarn`
1. Ensure there are no errors during `yarn`
1. Ensure you can run tests and app locally.
=> Issues developing against node 10

repositories/QuestionnaireRepository.js, repositories/QuestionnaireRepository.test.js, repositories/strategies/duplicateStrategy.js, repositories/strategies/duplicateStrategy.test.js, schema/resolvers.js, schema/resolversTests/duplication.test.js
Builds on #156 
This adds basic duplication of questionnaire which includes all sections, pages, answers etc.
Metadata, piping, routing, previous answer validations etc will be dealt with in separate PRs.
1. Checkout author branch `551-duplicate-questionnaire`
1. Ensure you can duplicate the questionnaire with all pages, sections, answers and validations (apart from max value against previous answers).
=> 551 duplicate questionnaire

app.js, middleware/launch.js, middleware/launch.test.js
It is not currently possible to pipe Date metadata into a questionnaire. Survey runner expects date values to be passed through in ISO format (yyyy-mm-dd) and author currently passes them in dd/mm/yyyy format.
The result is that the survey will launch but runner will throw a 403 authentication error (since the JWT token is considered invalid).
This fix formats Date values according to ISO format before they are passed into the claims of the JWT token. After applying this change, it should be possible to launch a questionnaire that pipes in a Date metadata value and have it show up within runner.
- Run the application using eq-compose
- Confirm that you cannot launch a questionnaire that pipes a Date metadata value
- Change the config of eq-compose so that it pulls down this branch's image …
=> Fix issue piping Date metadata.

package.json, schema/resolvers.js, schema/resolversTests/validation.test.js, tests/utils/graphql.js, yarn.lock
- Adds validation against a previous answer for earliest and latest date 
- Run tests
```
#Earliest date
mutation updateValidationRule($input: UpdateValidationRuleInput!) {
updateValidationRule(input: $input) {
...EarliestDateValidationRule
__typename
}
}
fragment EarliestDateValidationRule on EarliestDateValidationRule {
id
enabled
entityType
customDate: custom
offset {
value
unit
__typename
}
relativePosition
previousAnswer {
id
displayName
__typename
}
__typename
}
{
"input":{
"id":"3",
"earliestDateInput":{
"offset":{
"value":10,
"unit":"Days"
},
"relativePosition":"Before",
"entityType":"PreviousAnswer",
"custom":null,
"previousAnswer":"3"
}
}
}
```
```
#Latest date
mutation …
```
=> Add previous answer to earliest and latest date validation

repositories/strategies/routingStrategy.js, schema/resolvers.test.js
In the last PR I missed a bug where changing the comparator on the front end would create a new condition value for every change. This pr fixes that instance and adds a test to prevent it from recurring.
New test passes, and change makes sense.
=> Fixed bug with changing comparator creating new conVal

repositories/AnswerRepository.js, repositories/strategies/duplicateStrategy.js, repositories/strategies/duplicateStrategy.test.js, schema/resolvers.js, tests/utils/buildTestQuestionnaire.js
This implements:
1. Easier setup of complex questionnaires for tests
1. Duplication of piping when duplicating questionnaires and sections
1. Checkout author branch `551-duplicate-questionnaire`
1. Create a questionnaire with piping
1. Duplicate a questionnaire/section
1. Ensure that the piping is updated as expected:
1. When duplicating a section - references within a section are updated but external references are not
1. When duplicating a questionnaire - all references are updated.
=> 679  - Duplicate piping
